FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./package-lock.json ./package-lock.json

COPY ./package.json ./package.json

COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

COPY . .

RUN bun install
RUN bun run db:generate
RUN bun run build
RUN echo "Database URL is: $DATABASE_URL" 

EXPOSE 3000

CMD ["bun","run","start:web"]

