
FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app
COPY . .
RUN bun install
RUN cd packages/db && bunx prisma generate

RUN timeout 180 bun run build || echo "Using dev mode instead"

EXPOSE 3000
CMD ["bun", "run", "start:web"]