## build the docker image
## push the docker image to dockerhub
## SSH into our VM and start the new image

name: Deploy the backend
on:
  push:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: Saikat/todo-app-backend:${{ github.sha }}
          ##.sha is the hash of the current commit 
          ##Steps to deploy to a VM